server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://121.4.125.202:3306/skycloud?useSSL=false
    username: root
    password: xinyouMySQL99!
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo